theme: minima
title: "TBO Retro Collection"
url: "https://tboretro.github.io"

header_pages:
  - index.md
  - consoles.md
  - links.md
  - todo.md

collections:
  home_computers:
    output: true
  ibm_compatibles:
    output: true
  ibm_portables:
    output: true
  consoles:
    output: true
  consoles_mobile:
    output: true  # Do not forget to add new collections to the defaults below!

defaults:
  - scope:
      path: "static"
    values:
      hidden: true
  - scope:
      path: ""      # site-wide
      type: "pages"
    values:
      layout: "home"
  - scope:
      path: ""      # site-wide
      type: "home_computers"
    values:
      layout: "home"
  - scope:
      path: ""      # site-wide
      type: "ibm_compatibles"
    values:
      layout: "home"
  - scope:
      path: ""      # site-wide
      type: "ibm_portables"
    values:
      layout: "home"
  - scope:
      path: ""      # site-wide
      type: "consoles"
    values:
      layout: "home"
  - scope:
      path: ""      # site-wide
      type: "consoles_mobile"
    values:
      layout: "home"
